### ISSUE TITLE
Double ID's when creating with org-roam

### ISSUE THREAD

**Issue by p-ipo** [idanov/org-roam-logseq.el#1]
For some reason your solution creates double Properties&ID fields when creating nodes with org-roam capture tempaltes (org-roam-capture or org-roam-node-find).

Using default template im getting following as template result:

```
:PROPERTIES:
:ID:       BBE6C141-8022-4CB2-B748-E7451AFEF9B4
:END:
#+title: TestPage
:PROPERTIES:
:ID:       0A786F04-5429-4DD6-BEF7-2196E88E487A
:END:
```

**Comment by sbougerel** [comment]
It happens because the hook processes empty files as well. I'll submit a PR. You can test the changes on my fork if you're interested: https://github.com/sbougerel/org-roam-logseq.el

**Comment by ezmiller** [comment]
Will this go in?

**Comment by p-ipo** [comment]
Not sure how I should confirm the fix here at github, but according to my tests it fix works and I recomend accepting the pull req.
