### ISSUE TITLE
Error ‘org-element-at-point’ cannot be used in non-Org buffer

### ISSUE THREAD

**Issue by sbougerel** [idanov/org-roam-logseq.el#3]
The error occurs when batch processing notes, that have not yet been visited or converted using `bill/check-logseq`. It can occur for org-agenda queries, `org-roam-db-sync` queries and more.

### Steps to reproduce:

1. Add new notes in Logseq
2. In Emacs, call `org-roam-db-sync` (without first running `bill/check-logseq`)

### Full error shown in warnings:

```
Error (org-roam): Failed to process FILEPATH with error ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer FILEPATH> (fundamental-mode), skipping...
```

### Configuration:

```
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
Org mode: version 9.7 (9.7-??-38723463d)
Org-roam: version 5c06471
```

### Reason:

`org-element` requires the buffer to be an `org` buffer, however `org-roam-logseq-hook` runs on `find-file-hook` and `org-mode` is not guaranteed to be set.

### Solution

Make `org-roam-logseq-hook` run after `org-mode` instead.

**Comment by sbougerel** [comment]
I fixed it here: https://github.com/sbougerel/org-roam-logseq.el/commit/61dfab186e178d45c46bd41c7cec9b1779839699
Let me know if you'd like a PR, I can put it on a separate branch.

**Comment by idanov** [comment]
@sbougerel Sorry, I just saw this - sure, would love a PR to fix it :)

**Comment by idanov** [comment]
Fixed by https://github.com/idanov/org-roam-logseq.el/pull/2
